SELECT [Id]
      ,[Title]
      ,[RecruitAgencyName]
      ,[RecruitAgencyType]
      ,[MngDept]
      ,[MngName]
      ,[Field]
      ,[WorkDate_Type]
      ,[WorkDate_Nm]
      ,[WorkRegiontxt]
      ,[ReqDate_s]
      ,[ReqDate_e]
      ,[ReqType]
      ,[ReqType_Nm]
      ,[RegDate]
      ,[ModDate]
  FROM [EMS].[dbo].[JobInformation]
